import numpy as np
arr1 = np.empty(())
print("an uninitialized array")
print(arr1)
arr2 = np.zeros((2,2))
print("array with all elements as 0")
print(arr2)
arr3 = np.ones((2,2))
print("array with all elements as 1")
print(arr3)